### ISSUE TITLE
PRC

### ISSUE THREAD

**Issue by wangyongyuan** [ranxi2001/sol-balance-tracker#1]
你好 请问是用的哪个PRC啊。使用其他PRC会不会跟你使用的返回格式不一样

**Comment by ranxi2001** [comment]
我使用的是quick node solana rpc：https://dashboard.quicknode.com/endpoints

**Comment by wangyongyuan** [comment]
![1732533069502](https://github.com/user-attachments/assets/a34a0e92-318c-49aa-809a-207d59d59d4f)
![1732533079766](https://github.com/user-attachments/assets/5c51fecb-3a1a-4458-b8fc-3559d91af0ef)
是这个下面的这个LiveQuery吗，我使用这个返回结果好像不对，请问大佬使用的具体哪个API 是我上面那个LiveQuery吗

**Comment by ranxi2001** [comment]
不是啊 就是单独的 solana主网 rpc
![image](https://github.com/user-attachments/assets/02146252-b701-48b4-aa64-27c2cdad979b)
![image](https://github.com/user-attachments/assets/789209c5-488e-4a62-b668-e604a31afe7e)

**Comment by wangyongyuan** [comment]
![image](https://github.com/user-attachments/assets/79e16c62-25f4-434e-96f8-4eaf579e796a)
大佬，这一步点击到下一步需要选择一个API 现在有很多个

**Comment by ranxi2001** [comment]
我说了主网api啊，就是第一个 **main** ！这是无关本项目的问题，可以学习一下怎么用quick node。

**Comment by wangyongyuan** [comment]
好的 谢谢大佬 我去学习一下

**Comment by wangyongyuan** [comment]
哥 加你个微信可以吗 红包帮忙解决一下问题

**Comment by ranxi2001** [comment]
No.  Sorry for refuse !
搞区块链的赚钱很容易
时间很宝贵
不需要挣辛苦的钱 也不愿意做
你问问你老师吧
